stages:
    - build
building:
    stage: build
    tags:
        - test
    script:
          - cd ${CI_PROJECT_DIR}/src
          - make build
    artifacts:
        paths:
        - ${CI_PROJECT_DIR}/src/cat/s21_cat
        - ${CI_PROJECT_DIR}/src/grep/s21_grep
        expire_in: 30 days